<a href="https://colab.research.google.com/github/diegogonzalezc/notas_numpy_pandas/blob/main/Notas_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# **El array**

In [ ]:
lista=[1,2,3,4,5,6,7,8,9] 
arr = np.array(lista)#creación sencilla de un array
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]+arr[7] # operación de espacios del array


9

In [ ]:
matriz[0] # el valor 0  de la matriz es la primera fila de la misma

array([1, 2, 3])

In [ ]:
matriz[0,2] #si se quiere un valor específico se debe buscar señalando fila y columna

3

In [ ]:
arr[0:3] #esto es conocido como un slice que toma los valores del array desde 0 hasta 3

array([1, 2, 3])

In [ ]:
arr[::3] # en este caso le estamos diciendo al array que de steps de 3 

array([1, 4, 7])

# **Tipos de datos**

In [ ]:
arr= np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
arr= np.array([1,2,3,4], dtype= 'float64')
arr.dtype

dtype('float64')

In [ ]:
arr= np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [ ]:
arr= np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

## **Dimensiones**

In [ ]:
scalar= np.array(42) # en este caso tenemos un escalar, este no tiene dimensiones en el array
print(scalar)
scalar.ndim

42


0

In [ ]:
vector= np.array([1,2,3]) # los vectores tienen 1 dimensión
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz= np.array([[1,2,3],[4,5,6],[7,8,9]]) # las matrices independientemente del número de filas y columnas tienen dos dimensiones
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
tensor= np.array([[[1,2,3],[4,5,6]],[[9,10,11],[12,13,14]]]) # los tensores son composiciones matriciales con mas de 2 dimensiones 
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 9 10 11]
  [12 13 14]]]


3

In [ ]:
vector= np.array([1,2,3],ndmin=10) # en este caso con ndim= 10 podemos obtener el numero de dimensiones deseado, notar que el numero de corchetes cuadrados es igual al  numero de dimensiones
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0) #np.expand me suma una dimension más
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector,vector.ndim)
vector_2 = np.squeeze(vector)#squeeze me disminuye el numero de dimensiones al menor posible
print(vector_2,vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [ ]:
tensor= np.array([[[1,2,3],[4,5,6]],[[9,10,11],[12,13,14]]],ndmin=5)

print(tensor)
tensor.ndim

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 9 10 11]
    [12 13 14]]]]]


5

In [ ]:
print(tensor,tensor.ndim)
tensor_2 = np.squeeze(tensor)
print(tensor_2,tensor_2.ndim)

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 9 10 11]
    [12 13 14]]]]] 5
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 9 10 11]
  [12 13 14]]] 3


# **Creando arrays**

In [ ]:
np.arange(0,10)# se definen números del 0 al 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2) #se definen numeros del 0 al 20 con un step de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros((10,10)) # creción de una matríz de 0 de 10x10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,10))# creción de una matríz de 1 de 10x10

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,10) #es un rango de 0, a 10 con 10 valores

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(4)#matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(4,4)# es una creación de datos de 4x4

array([[0.91174316, 0.71232271, 0.78080443, 0.29327866],
       [0.13935932, 0.68168586, 0.2967998 , 0.04171163],
       [0.69957253, 0.352238  , 0.87018685, 0.04154484],
       [0.18894594, 0.57347393, 0.03678676, 0.24389936]])

In [ ]:
np.random.randint(1,100,(10,10))# estos son enteros de 1 a 100 en una matriz de 10x10

array([[25, 24, 97, 82, 40, 24, 25, 52, 57, 43],
       [13, 58,  9, 96, 35, 79, 51, 89, 64, 67],
       [45, 18, 35, 59, 71, 45, 11, 40, 10, 49],
       [71, 47, 33, 36, 47, 95, 53, 58, 87, 25],
       [78, 12, 20, 21, 72, 28, 65, 20, 27, 73],
       [ 1, 45, 63,  3, 67, 89, 36, 87, 27, 12],
       [39,  7, 33, 38, 22, 51, 46, 10, 56, 56],
       [11, 53, 17, 70, 51, 98, 94, 43, 29, 79],
       [52, 96, 97, 63, 14, 48, 14, 69, 15, 26],
       [50, 80,  2, 43, 91, 30, 57, 44, 79, 81]])

# **Shape y reshape**



In [ ]:
arr=np.random.randint(0,10,(3,2))
arr.shape

(3, 2)

In [ ]:
arr

array([[9, 7],
       [3, 6],
       [9, 5]])

In [ ]:
arr.reshape(1,6)# con reshape se puede cambiar la estructura de un array pero conservando el numero de valores en su interior en este caso paso de 3x 2  a 6 x 1

array([[9, 7, 3, 6, 9, 5]])

In [ ]:
np.reshape(arr,(2,3))

array([[9, 7, 3],
       [6, 9, 5]])

In [ ]:
np.reshape(arr,(2,3),'C') # 'C' esuna manera en la cual se obtiene la informacion la cual es la predefinida poor pandas pero tambien podria ser tipo f

array([[9, 7, 3],
       [6, 9, 5]])

In [ ]:
np.reshape(arr,(2,3),'F')

array([[9, 9, 6],
       [3, 7, 5]])

# **Funciones principales**

In [ ]:
matriz=np.random.randint(1,20,(2,5))
matriz

array([[ 5,  8, 15,  3,  3],
       [17, 16, 12,  5,  6]])

In [ ]:
matriz.max() # mayor valor de la matriz

17

In [ ]:
matriz.max(1) # mayor valor de la matriz en las filas o eje 1

array([15, 17])

In [ ]:
matriz.argmax(1)# me entrega el indice donde se encuentra el mayor valor.

array([2, 0])

In [ ]:
matriz.ptp(0)# la diferencia o el pico mas alto entre los datos de las columnas

array([12,  8,  3,  2,  3])

In [ ]:
arr=np.reshape(matriz,(1,10))

In [ ]:
arr.sort() #organiza de menor a mayor
arr

array([[ 3,  3,  5,  5,  6,  8, 12, 15, 16, 17]])

In [ ]:
np.percentile(arr,50)# es el percentil 50 de mis datos

7.0

In [ ]:
np.median(arr)

7.0

In [ ]:
np.median(matriz,0)# mediana en columnas

array([ 5.5,  7.5, 10. , 10.5, 11.5])

In [ ]:
np.median(matriz,1)#mediana en filas

array([ 5., 15.])

In [ ]:
np.median(matriz)

7.0

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [ ]:
b=np.expand_dims(b,axis=0)# esto lo hacemos para que las dimensiones de los dos arrays coincidan y se pueda concatenar

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#para hacerlo en el eje 1 se puede o hacer resample o usar la transpuesta
np.concatenate((a,(b.T)),axis=1)


array([[1, 2, 5],
       [3, 4, 6]])

# **COPY**

In [ ]:
arr=np.arange(0,11)
arr



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_ar=arr[0:6]
trozo_ar

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_ar[:]=0
trozo_ar

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr # como modifique una parte del array se modificó el original, esto es inconveniente y es necesario hacer copy para evitar esto

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy=arr.copy()

In [ ]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

# **Condiciones**

In [ ]:
arr=np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
indices_cond=arr > 5 # es posible crear un indice con unas condiciones para despues hacer slice


In [ ]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
indices_cond=[(arr > 5) & (arr < 9)] #concatenando varias condiciones

In [ ]:
arr[indices_cond]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr>5]=99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [ ]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

# **Operaciones**

In [ ]:
lista=[1,2]

In [ ]:
lista*2

[1, 2, 1, 2]

In [ ]:
arr=np.arange(0,10)
arr2=np.copy(arr)


In [ ]:
arr*2 #es totalmente distitno a una lista, el array es muy poderoso

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
matriz= arr.reshape(5,2)
matriz2= matriz.copy()

In [ ]:
np.matmul(matriz,matriz2.T)#producto punto

array([[  1,   3,   5,   7,   9],
       [  3,  13,  23,  33,  43],
       [  5,  23,  41,  59,  77],
       [  7,  33,  59,  85, 111],
       [  9,  43,  77, 111, 145]])

In [ ]:
matriz @ matriz2.T#producto punto

array([[  1,   3,   5,   7,   9],
       [  3,  13,  23,  33,  43],
       [  5,  23,  41,  59,  77],
       [  7,  33,  59,  85, 111],
       [  9,  43,  77, 111, 145]])

# **Series y Dataframes**

In [ ]:
psg=pd.Series(['Navas','Mbappe','Neymar','Messi'],index=[1,7,10,30])
psg

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
dict={1:'Navas',7:'Mbappe',10:'Neymar',30:'Messi'} # es la misma manera de crear una serie
pd.Series(dict)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
dict={'jugador':['Navas','Mbappe','Neymar','Messi'], #cuando ya no solo son indice y llave se debe crear un dataframe
      'Altura':[183.0,180.0,175.0,165.0],
      'Goles':[0,20,15,3]}

In [ ]:
df_psg=pd.DataFrame(dict,index=[1,7,10,30])
df_psg

jugador  Altura  Goles
1    Navas   183.0      0
7   Mbappe   180.0     20
10  Neymar   175.0     15
30   Messi   165.0      3

In [ ]:
from google.colab import drive # es indispensable hacer el mount de drive para poder acceder a los archivos que acá se contienen
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
%cd '/content/drive/MyDrive/Colab Notebooks/Curso platzi pandas y numpy/' 
# con %cd cambio el directorio y pongo el que me interesa, en este caso donde tengo el archivo que voy a cargar

/content/drive/MyDrive/Colab Notebooks/Curso platzi pandas y numpy


In [ ]:
%ls

 10.series_dataframe.ipynb
'11. cargando archivos.ipynb'
'12.Manejo de datos nulos.ipynb'
'13.Filtrado por condiciones.ipynb'
 14.funciones.ipynb
 15.groupby.ipynb
'16Merge y concat.ipynb'
'17.pivot y melt.ipynb'
 18.apply.ipynb
'1.El array.ipynb'
'2.tipos de datos.ipynb'
 3.dimesniones
'4.creando arrays.ipynb'
'5.Shape y reshape.ipynb'
'6.Funciones principales.ipynb'
 7.COPY.ipynb
 8.coditions.ipynb
 9.operaciones.ipynb
 bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv
 Notas_numpy_pandas.ipynb


In [ ]:
df_books=pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',sep=',',header=0) # sencillamente pd.read_csv(el_nombre_del_archivo.csv,spr="(aca puede ser punto o coma o | depende del archivo)", header=0)
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books[0:4]# muy similar a numpy se pueden hacer slice 

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [ ]:
df_books[['Name','Author']] # tambien filtrar por columnas, notar que se tiene dos [[]] esto para devolver un dataframe

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  
0                    JJ Smith  
1                Stephen King  
2          Jordan B. Peterson  
3               George Orwell  
4    National Geographic Kids  
..                        ...  
545               Jeff Kinney  
546               Jen Sincero  
547               Jen Sincero  
548               Jen Sincero  
549               Jen Sincero  

[550 rows x 2 columns]

In [ ]:
df_books.loc[0:4,['Author']]# del lado izquierdo de las comas tenemos las filas a la derecha las columnas Loc solo se usa con labels

Author
0                  JJ Smith
1              Stephen King
2        Jordan B. Peterson
3             George Orwell
4  National Geographic Kids

In [ ]:
df_books.iloc[0:4,[1]] #oloc se usa con los indices es decir numeros

Author
0            JJ Smith
1        Stephen King
2  Jordan B. Peterson
3       George Orwell

In [ ]:
df_books.drop('Genre',axis =1, inplace =True)# se elimina en el sitio la columna
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

In [ ]:
df_books.drop(0,axis=0).head() # acá podemos eliminar la fila 0 



Name  \
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   
5      A Dance with Dragons (A Song of Ice and Fire)   

                     Author  User Rating  Reviews  Price  Year  
1              Stephen King          4.6     2052     22  2011  
2        Jordan B. Peterson          4.7    18979     15  2018  
3             George Orwell          4.7    21424      6  2017  
4  National Geographic Kids          4.8     7665     12  2019  
5       George R. R. Martin          4.4    12643     11  2011

In [ ]:
df_books.drop(range(0,10),axis=0).head()# se pueden eliminar filas con rangos

Name             Author  \
10                          A Man Called Ove: A Novel    Fredrik Backman   
11  A Patriot's History of the United States: From...   Larry Schweikart   
12                            A Stolen Life: A Memoir      Jaycee Dugard   
13                   A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
14  Act Like a Lady, Think Like a Man: What Men Re...       Steve Harvey   

    User Rating  Reviews  Price  Year  
10          4.6    23848      8  2017  
11          4.6      460      2  2010  
12          4.6     4149     32  2011  
13          4.5     5153      5  2018  
14          4.6     5013     17  2009

In [ ]:
data=np.arange(0,df_books.shape[0])# esta es una lista con todos los valores desde 0 hasta el ultimo de las filas.
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
df_books['Rango']=data # se crea una nueva columna con el rango Asignando en orden el valor en Range
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  Rango  
0                    JJ Smith          4.7    17350      8  2016      0  
1                Stephen King          4.6     2052     22  2011      1  
2          Jordan B. Peterson          4.7    18979     15  2018      2  
3               George Orwell          4.7    21424      6  2017      3  
4    National Geographic Kids          4.8     7665     12  2019      4  
..                        ...          ...      ...    ...   ...    ...  
545               Jeff Kinney          4.9     9413      8  2019    545  
546               Jen Sincero          4.7    14331      8  2016    546  
547               Jen Sincero          4.7    14331      8  2017    547  
548               Jen Sincero          4.7    14331      8  2018    548  
549               Jen Sincero          4.7    14331      8  2019    549  

[550 rows x 7 columns]

# **Manejo de datos nulos**


In [ ]:
dict={'Col1':[1,2,3,np.nan],
      'Col2':[4,np.nan,6,7,],
      'Col3':['a','b','b',None]}

In [ ]:
df=pd.DataFrame(dict)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     b
3   NaN   7.0  None

In [ ]:
df.isnull()# sale true a los valores nulos dentro del dataframe

Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [ ]:
df.isnull()*1 #se puede hacer para que tenga valores de 1 y o

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [ ]:
df.fillna('missing') #se puede llenar con algun valor

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  missing        b
2      3.0      6.0        b
3  missing      7.0  missing

In [ ]:
df.fillna(df.mean()) # llena los valores nulos con la media, claramente los strings no los puede operar

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     b
3   2.0  7.000000  None

In [ ]:
df.interpolate()#asume los valores que hacen falta

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     b
3   3.0   7.0  None

In [ ]:
df.dropna() # elimina las filas con valores nulos

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    b

# **Filtrado por condiciones**

In [ ]:
%cd '/content/drive/My Drive/Colab Notebooks/Curso platzi pandas y numpy/'

df_books=pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')
df_books.head(2)

/content/drive/My Drive/Colab Notebooks/Curso platzi pandas y numpy


Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [ ]:
mayor_2016=df_books['Year']>2016 # este es un filtro en el cual solo se toman los datos de los libros despues del 2016
mayor_2016

0      False
1      False
2       True
3       True
4       True
       ...  
545     True
546    False
547     True
548     True
549     True
Name: Year, Length: 550, dtype: bool

In [ ]:
df_books[mayor_2016] # se aplica el filtro a la dataframe
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
genere_fiction=df_books['Genre']=='Fiction'
genere_fiction

0      False
1       True
2      False
3       True
4      False
       ...  
545     True
546    False
547    False
548    False
549    False
Name: Genre, Length: 550, dtype: bool

In [ ]:
df_books[mayor_2016 & genere_fiction] # se hace un filtro con las dos condiciones anteriores

Name             Author  \
3                               1984 (Signet Classics)      George Orwell   
7                       A Gentleman in Moscow: A Novel        Amor Towles   
10                           A Man Called Ove: A Novel    Fredrik Backman   
13                    A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
40            Brown Bear, Brown Bear, What Do You See?    Bill Martin Jr.   
..                                                 ...                ...   
509                              To Kill a Mockingbird         Harper Lee   
529  What Should Danny Do? (The Power to Choose Ser...          Adir Levy   
534                            Where the Crawdads Sing        Delia Owens   
544                                             Wonder      R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)        Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
3            4.7    21424      6  2017  Fiction  
7            4.7    19699     15  2017  Fiction  
10           4.6    23848      8  2017  Fiction  
13           4.5     5153      5  2018  Fiction  
40           4.9    14344      5  2017  Fiction  
..           ...      ...    ...   ...      ...  
509          4.8    26234      7  2019  Fiction  
529          4.8     8170     13  2019  Fiction  
534          4.8    87841     15  2019  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[65 rows x 7 columns]

In [ ]:
df_books[(df_books['Year']>2016) & (df_books['Genre']=='Fiction')]# esto es lo mismo que el filtro anterior pero en una sola linea de codifo

Name             Author  \
3                               1984 (Signet Classics)      George Orwell   
7                       A Gentleman in Moscow: A Novel        Amor Towles   
10                           A Man Called Ove: A Novel    Fredrik Backman   
13                    A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
40            Brown Bear, Brown Bear, What Do You See?    Bill Martin Jr.   
..                                                 ...                ...   
509                              To Kill a Mockingbird         Harper Lee   
529  What Should Danny Do? (The Power to Choose Ser...          Adir Levy   
534                            Where the Crawdads Sing        Delia Owens   
544                                             Wonder      R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)        Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
3            4.7    21424      6  2017  Fiction  
7            4.7    19699     15  2017  Fiction  
10           4.6    23848      8  2017  Fiction  
13           4.5     5153      5  2018  Fiction  
40           4.9    14344      5  2017  Fiction  
..           ...      ...    ...   ...      ...  
509          4.8    26234      7  2019  Fiction  
529          4.8     8170     13  2019  Fiction  
534          4.8    87841     15  2019  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[65 rows x 7 columns]

In [ ]:
df_books[mayor_2016 & ~genere_fiction] #con ~ se niega la condicion

Name  \
2              12 Rules for Life: An Antidote to Chaos   
4    5,000 Awesome Facts (About Everything!) (Natio...   
8        A Higher Loyalty: Truth, Lies, and Leadership   
26                  Astrophysics for People in a Hurry   
32                                            Becoming   
..                                                 ...   
526                                      What Happened   
536  Whose Boat Is This Boat?: Comments That Don't ...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                               Author  User Rating  Reviews  Price  Year  \
2                  Jordan B. Peterson          4.7    18979     15  2018   
4            National Geographic Kids          4.8     7665     12  2019   
8                         James Comey          4.7     5983      3  2018   
26                Neil deGrasse Tyson          4.7     9374      9  2017   
32                     Michelle Obama          4.8    61133     11  2018   
..                                ...          ...      ...    ...   ...   
526            Hillary Rodham Clinton          4.6     5492     18  2017   
536  The Staff of The Late Show with
          4.6     6669     12  2018   
547                       Jen Sincero          4.7    14331      8  2017   
548                       Jen Sincero          4.7    14331      8  2018   
549                       Jen Sincero          4.7    14331      8  2019   

           Genre  
2    Non Fiction  
4    Non Fiction  
8    Non Fiction  
26   Non Fiction  
32   Non Fiction  
..           ...  
526  Non Fiction  
536  Non Fiction  
547  Non Fiction  
548  Non Fiction  
549  Non Fiction  

[85 rows x 7 columns]


# **Funciones**

In [ ]:
df_books.info() # con este comando podemos saber toda la informacion de los dataframes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [ ]:
df_books.describe() # aca podemos revisar los datos estadisticos para ir identificando los datos dentro de la base de datos

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [ ]:
df_books.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

In [ ]:
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [ ]:
df_books=df_books.append(df_books.head(1),0) #duplicamos la primera fila y se encuentra en la primera y la ultima
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[551 rows x 7 columns]

In [ ]:
df_books.drop_duplicates() #elimina valores duplicados

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.sort_values('Year', ascending= False)# organizar valores de la columna año en orden descendente

Name                 Author  \
179                       If Animals Kissed Good Night      Ann Whitford Paul   
294  School Zone - Big Preschool Workbook - Ages 4 ...            School Zone   
263    P is for Potty! (Sesame Street) (Lift-the-Flap)        Naomi Kleinberg   
489                   The Wonderful Things You Will Be  Emily Winfield Martin   
267             Player's Handbook (Dungeons & Dragons)       Wizards RPG Team   
..                                                 ...                    ...   
160                  Have a Little Faith: A True Story            Mitch Albom   
512                             True Compass: A Memoir      Edward M. Kennedy   
513               Twilight (The Twilight Saga, Book 1)        Stephenie Meyer   
78   Divine Soul Mind Body Healing and Transmission...           Zhi Gang Sha   
459        The Shack: Where Tragedy Confronts Eternity       William P. Young   

     User Rating  Reviews  Price  Year        Genre  
179          4.8    16643      4  2019      Fiction  
294          4.8    23047      6  2019  Non Fiction  
263          4.7    10820      5  2019  Non Fiction  
489          4.9     8842     10  2019      Fiction  
267          4.8    16990     27  2019      Fiction  
..           ...      ...    ...   ...          ...  
160          4.8     1930      4  2009  Non Fiction  
512          4.5      438     15  2009  Non Fiction  
513          4.7    11676      9  2009      Fiction  
78           4.6       37      6  2009  Non Fiction  
459          4.6    19720      8  2009      Fiction  

[551 rows x 7 columns]

# **Groupby**



In [ ]:
df_books.groupby('Author').count() #groupby sirve para agrupar datos, en este caso el autor y le damos la indicacion de contar

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [ ]:
df_books.groupby('Author').agg(['min','max']) # como opcion con agg podemos subdividir mas aun los datos en este caso por autor y buscar el maximo y minimo

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

In [ ]:
df_books.groupby('Author').agg({'Reviews':['min','max'],'User Rating':'sum'}) # tambien con corchetes tipo dict podemos seleccionar especificamente las columnas de nuestro interes

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [ ]:
df_books.groupby(['Author','Year']).count() # tambien es posible agrupar con dos indices

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]

# **Merge y concat**

In [ ]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
 'B':['B0','B1','B2','B3'],
 'C':['C0','C1','C2','C3'],
 'D':['D0','D1','D2','D3']})

df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7'],
 'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [ ]:
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
pd.concat([df1,df2],ignore_index=True)# con el ignore_index se reinicia el indice para que no haya repetidos

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
pd.concat([df1,df2],axis=1) # en caso que se quiera hacer por las columnas

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

In [ ]:
izq=pd.DataFrame({'key':['k4','k5','k6','k7'],
  'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7']})

der=pd.DataFrame({'key':['k4','k5','k6','k7'],
  'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [ ]:
izq.merge(der, on = 'key') # aca estamos haciendo el merge en la columna key que es identica en los dos dataframes

key   A   B   C   D
0  k4  A4  B4  C4  D4
1  k5  A5  B5  C5  D5
2  k6  A6  B6  C6  D6
3  k7  A7  B7  C7  D7

In [ ]:
izq=pd.DataFrame({'key':['k4','k5','k6','k7'],
  'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7']})
der=pd.DataFrame({'key_2':['k4','k5','k6','k7'],
  'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [ ]:
izq.merge(der, left_on='key',right_on='key_2')# em este caso le damos la instruccion de por donde se debe adherir en cada uno de los dataframes

key   A   B key_2   C   D
0  k4  A4  B4    k4  C4  D4
1  k5  A5  B5    k5  C5  D5
2  k6  A6  B6    k6  C6  D6
3  k7  A7  B7    k7  C7  D7

In [ ]:
izq=pd.DataFrame({'key':['k4','k5','k6','k7'],
  'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7']})
der=pd.DataFrame({'key_2':['k4','k5','k6',np.nan],
  'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [ ]:
izq.merge(der, left_on='key',right_on='key_2')# acá se está  haciendo un inner, por esta razon ya que key_2 no tiene k7 lo elimina

key   A   B key_2   C   D
0  k4  A4  B4    k4  C4  D4
1  k5  A5  B5    k5  C5  D5
2  k6  A6  B6    k6  C6  D6

In [ ]:
izq.merge(der, left_on='key',right_on='key_2',how='right')# cuando le damos right le decimos que tome los datos de el dataframe der el cual no tiene k7

key    A    B key_2   C   D
0   k4   A4   B4    k4  C4  D4
1   k5   A5   B5    k5  C5  D5
2   k6   A6   B6    k6  C6  D6
3  NaN  NaN  NaN   NaN  C7  D7

In [ ]:
izq=pd.DataFrame({'A':['A0','A1','A2'],
 'B':['B0','B1','B2']},
 index=['k0','k1','k2'])

der=pd.DataFrame({'C':['C0','C1','C2'],
 'D':['D0','D1','D2']},
 index=['k0','k2','k3'])

In [ ]:
izq.join(der)# este funciona por los indices, esa es la diferencia con merge y join

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1  NaN  NaN
k2  A2  B2   C1   D1

In [ ]:
izq.join(der, how='inner')# este funciona por los indices, esa es la diferencia con merge y join

A   B   C   D
k0  A0  B0  C0  D0
k2  A2  B2  C1  D1

# **Pivot y Melt**


In [ ]:
df_books.pivot_table(index='Author',columns='Genre',values='User Rating')# Se cambia filas por columnas es decir fiction pasa a ser una columna y el valor es user_rating

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [ ]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='mean') # en este caso se ve mucha mas utilidad haciendo los promedios por año de user rating


Year             2009   2010      2011      2012      2013      2014  \
Genre                                                                  
Fiction      4.591667  4.615  4.619048  4.495238  4.545833  4.631034   
Non Fiction  4.576923  4.520  4.513793  4.558621  4.561538  4.609524   

Year             2015      2016      2017      2018      2019  
Genre                                                          
Fiction      4.652941  4.715789  4.737500  4.738095  4.820000  
Non Fiction  4.645455  4.656250  4.588462  4.617241  4.686667

In [ ]:
df_books[['Name','Genre']].head(5)

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [ ]:
df_books[['Name','Genre']].head(5).melt() # melt toma los valores de las columnas y se los asocia a cada uno de los datos del data frame

variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

In [ ]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction
550  2016    Genre  Non Fiction

[551 rows x 3 columns]

# **Apply**

In [ ]:
def two_times(value):
  return value*2

In [ ]:
df_books['Rating_2']=df_books['User Rating'].apply(two_times) # en este caso se aplicará a la funcion a rating y se pondrá el resultado en la nueva columna
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   

     Rating_2  
0         9.4  
1         9.2  
2         9.4  
3         9.4  
4         9.6  
..        ...  
546       9.4  
547       9.4  
548       9.4  
549       9.4  
0         9.4  

[551 rows x 8 columns]

In [ ]:
df_books['Rating_2']=df_books['User Rating'].apply(lambda x:x*2) # lambda es una funcion implicita, es posible hacerla en el mismo sitio y funciona igual
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   

     Rating_2  
0         9.4  
1         9.2  
2         9.4  
3         9.4  
4         9.6  
..        ...  
546       9.4  
547       9.4  
548       9.4  
549       9.4  
0         9.4  

[551 rows x 8 columns]

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   

     Rating_2  
0         9.4  
1         9.2  
2         9.4  
3         9.4  
4         9.6  
..        ...  
546       9.4  
547       9.4  
548       9.4  
549       9.4  
0         9.4  

[551 rows x 8 columns]

In [ ]:
df_books['Rating_2']=df_books.apply(lambda x: x['Rating_2'] *2 if x['Genre'] == "Fiction" else x['User Rating'],axis=1)
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   

     Rating_2  
0         4.7  
1        18.4  
2         4.7  
3        18.8  
4         4.8  
..        ...  
546       4.7  
547       4.7  
548       4.7  
549       4.7  
0         4.7  

[551 rows x 8 columns]